# Generated by Django 5.0.2 on 2024-05-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
