# Generated by Django 5.0.2 on 2024-02-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='user_id',
            new_name='user',
        ),
    ]
