# Generated by Django 5.0.2 on 2024-05-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_user_id_positions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='type',
            field=models.CharField(choices=[('401K', '401K'), ('ROTH', 'Roth IRA'), ('INDIVIDUAL', 'Individual'), ('CRYPTO', 'Cryptocurrency')], default='INDIVIDUAL', max_length=10),
        ),
    ]
