# Generated by Django 5.0.2 on 2024-05-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_positions_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='purchased_date',
        ),
    ]
